mod 'puppetlabs-stdlib', '8.5.0'
mod 'puppetlabs-apt', '9.0.1'
mod 'puppet-kibana', '7.0.1'
mod 'puppet-elasticsearch', '8.0.2'
mod 'richardc-datacat', '0.6.2'
mod 'puppet-elastic_stack', '8.0.2'
mod 'puppet-yum', '6.1.0'
mod 'elastic-logstash', '6.1.5'
mod 'puppetlabs-java', '9.0.1'
mod 'molly-elk',
  :git => 'https://github.com/molmili/molly-elk.git'
